name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev, preprod, prod)'
        required: true
        default: 'dev'

jobs:
  terraform-execution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.4.0'

    - name: Set Working Directory
      id: set-working-directory
      run: |
        echo "## Setting Working Directory"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Changing to directory $ENV_PATH"
        cd $ENV_PATH || exit 1
        echo "## Current Directory"
        pwd
        echo "## List Files"
        ls -la
        echo "## Checking if Terraform configuration files exist"
        if ls *.tf 1> /dev/null 2>&1; then
          echo "Terraform configuration files found"
          echo "TF_FILES_EXIST=true" >> $GITHUB_ENV
        else
          echo "No Terraform configuration files found"
          echo "TF_FILES_EXIST=false" >> $GITHUB_ENV
        fi

    - name: Create terraform.tfvars
      if: env.TF_FILES_EXIST == 'true'
      run: |
        echo "## Creating terraform.tfvars"
        echo "client_id = \"${{ secrets.ARM_CLIENT_ID }}\"" > terraform.tfvars
        echo "client_secret = \"${{ secrets.ARM_CLIENT_SECRET }}\"" >> terraform.tfvars
        echo "subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" >> terraform.tfvars
        echo "tenant_id = \"${{ secrets.ARM_TENANT_ID }}\"" >> terraform.tfvars
        echo "## Contents of terraform.tfvars:"
        cat terraform.tfvars

    - name: Initialize Terraform
      if: env.TF_FILES_EXIST == 'true'
      run: |
        echo "## Initializing Terraform"
        terraform init \
          -backend-config="resource_group_name=${{ secrets.STATE_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.STATE_CONTAINER_NAME }}" \
          -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate"
        echo "## Terraform Initialized"

    - name: Plan Terraform Changes
      if: env.TF_FILES_EXIST == 'true'
      run: |
        echo "## Planning Terraform Changes"
        terraform plan -var-file=terraform.tfvars -out=tfplan
        echo "## Terraform Plan Completed"

    - name: Apply Terraform Changes
      if: env.TF_FILES_EXIST == 'true'
      run: |
        echo "## Applying Terraform Changes"
        terraform apply -auto-approve tfplan
        echo "## Terraform Apply Completed"
