name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (dev, preprod, prod)'
        required: true
        default: dev

jobs:
  terraform-execution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.4.0'

    - name: Create terraform.tfvars
      run: |
        ENV_PATH="./environments/${{ github.event.inputs.environment }}/terraform.tfvars"
        echo "client_id = \"${{ secrets.ARM_CLIENT_ID }}\"" > $ENV_PATH
        echo "client_secret = \"${{ secrets.ARM_CLIENT_SECRET }}\"" >> $ENV_PATH
        echo "subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" >> $ENV_PATH
        echo "tenant_id = \"${{ secrets.ARM_TENANT_ID }}\"" >> $ENV_PATH
        echo "object_id = \"${{ secrets.ARM_OBJECT_ID }}\"" >> $ENV_PATH
        ls -la
        cat $ENV_PATH

    - name: Set Working Directory
      run: |
        echo "## Setting Working Directory"
        cd ./path-to-your-terraform-config-directory  # Update this path
        pwd

    - name: Initialize Terraform
      run: |
        echo "## Initializing Terraform"
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        ENVIRONMENT=${{ github.event.inputs.environment }}
        terraform init \
          -backend-config="resource_group_name=${{ secrets.STATE_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.STATE_CONTAINER_NAME }}" \
          -backend-config="key=${REPO_NAME}/${ENVIRONMENT}/terraform.tfstate" \
          -reconfigure
        echo "## Terraform Initialized"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Plan Terraform Changes
      run: |
        echo "## Planning Terraform Changes"
        terraform plan -var-file="./environments/${{ github.event.inputs.environment }}/terraform.tfvars" -out=tfplan
        echo "## Terraform Plan Completed"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Apply Terraform Changes
      run: |
        echo "## Applying Terraform Changes"
        terraform apply -auto-approve tfplan
        echo "## Terraform Apply Completed"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
