name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (dev, preprod, prod)'
        required: true
        default: 'dev'

jobs:
  terraform-execution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.4.0'

    - name: Set Working Directory
      id: set-working-directory
      run: |
        echo "## Setting Working Directory"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Changing to directory $ENV_PATH"
        cd $ENV_PATH || exit 1
        echo "## Current Directory"
        pwd
        echo "## List Files"
        ls -la

    - name: Create terraform.tfvars
      run: |
        echo "## Creating terraform.tfvars"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "client_id = \"${{ secrets.ARM_CLIENT_ID }}\"" > ${ENV_PATH}/terraform.tfvars
        echo "client_secret = \"${{ secrets.ARM_CLIENT_SECRET }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "tenant_id = \"${{ secrets.ARM_TENANT_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "object_id = \"${{ secrets.ARM_OBJECT_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "## Contents of terraform.tfvars:"
        cat ${ENV_PATH}/terraform.tfvars

    - name: Verify terraform.tfvars Location
      run: |
        echo "## Verifying terraform.tfvars Location"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Listing Files in $ENV_PATH"
        ls -la $ENV_PATH

    - name: Initialize Terraform
      run: |
        echo "## Initializing Terraform"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        cd $ENV_PATH || exit 1
        terraform init \
          -backend-config="backend/${{ github.event.inputs.environment }}.tfbackend"
        echo "## Terraform Initialized"

    - name: Plan Terraform Changes
      run: |
        ls -la
        echo "## Planning Terraform Changes"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        cd $ENV_PATH && terraform plan -var-file=terraform.tfvars -out=tfplan
        echo "## Terraform Plan Completed"

    - name: Apply Terraform Changes
      run: |
        echo "## Applying Terraform Changes"
        terraform apply -auto-approve tfplan
        echo "## Terraform Apply Completed"
