name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (dev, preprod, prod)'
        required: true
        default: 'dev'

jobs:
  terraform-execution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.4.0'

    - name: Set Working Directory
      id: set-working-directory
      run: |
        echo "## Setting Working Directory"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Changing to directory $ENV_PATH"
        cd $ENV_PATH || exit 1
        echo "## Current Directory"
        pwd
        echo "## List Files"
        ls -la

    - name: Create terraform.tfvars
      run: |
        echo "## Creating terraform.tfvars"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "client_id = \"${{ secrets.ARM_CLIENT_ID }}\"" > ${ENV_PATH}/terraform.tfvars
        echo "client_secret = \"${{ secrets.ARM_CLIENT_SECRET }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "tenant_id = \"${{ secrets.ARM_TENANT_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "object_id = \"${{ secrets.ARM_OBJECT_ID }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "environment_name = \"${{ github.event.inputs.environment }}\"" >> ${ENV_PATH}/terraform.tfvars
        echo "## Contents of terraform.tfvars:"
        cat ${ENV_PATH}/terraform.tfvars

    - name: Verify terraform.tfvars Location
      run: |
        echo "## Verifying terraform.tfvars Location"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Listing Files in $ENV_PATH"
        ls -la $ENV_PATH

    - name: Initialize Terraform
      run: |
        echo "## Initializing Terraform"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Changing to directory $ENV_PATH"
        cd $ENV_PATH || exit 1
        echo "## Listing Files in $ENV_PATH"
        ls -la
        echo "## Backend Config:"
        echo "resource_group_name=${{ secrets.STATE_RESOURCE_GROUP_NAME }}"
        echo "storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}"
        echo "container_name=${{ secrets.STATE_CONTAINER_NAME }}"
        echo "key=${{ github.event.inputs.environment }}/terraform.tfstate"
        terraform init \
          -backend-config="resource_group_name=${{ secrets.STATE_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.STATE_CONTAINER_NAME }}" \
          -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate"
        echo "## Terraform Initialized"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Plan Terraform Changes
      run: |
        echo "## Planning Terraform Changes"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        echo "## Environment Path: $ENV_PATH"
        pwd
        ls -la
        cd $ENV_PATH
        ls -la
        terraform plan -var-file=terraform.tfvars -out=tfplan
        echo "## Terraform Plan Completed"

    - name: Apply Terraform Changes
      run: |
        echo "## Applying Terraform Changes"
        ENV_PATH="./environments/${{ github.event.inputs.environment }}"
        cd $ENV_PATH
        terraform apply -auto-approve tfplan
        echo "## Terraform Apply Completed"
